"""2HM_SHOPP

Revision ID: 265ed4134a57
Revises: 
Create Date: 2024-03-11 21:26:58.837605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265ed4134a57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_imei', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['auto_imei'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auto_imei')

    # ### end Alembic commands ###
