"""2HM_SHOP

Revision ID: ba115cfc432b
Revises: 
Create Date: 2024-03-05 11:07:31.626788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba115cfc432b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('describe', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extend', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail', schema=None) as batch_op:
        batch_op.drop_column('extend')
        batch_op.drop_column('describe')

    # ### end Alembic commands ###
